# 1. What does Pandas stand for?
### Panel Data and Python Data Analysis

# 2. What are the 2 collections used in Pandas?
### Panda Series and Panda DataFrames

# 3. Name 4 things Pandas can do for us.
### Load, manipulate, prepare, & analyze.

# 4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
### inplace = True

# 5. What is a CSV
### Data separated by commas; can also be separated by semi-colon, colon, vertical bar & tab. 

# 6. When cleaning data what values do we not like in our data?
### Null

In [154]:
# Do NOT do questions 10, 17-19 
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

arrayA = np.arange(12)

arrayB = np.array([[0, 1], [2, 3]])
arrayD = np.array([[5, 6]])
arrayE = np.array([[4, 7], [9, 10], [12, 11]])

arrayC = np.concatenate((arrayB, arrayD, arrayE), axis=0)
arrayAReshape = arrayC.reshape(2, 3, 2)

print(arrayAReshape)

[[[ 0  1]
  [ 2  3]
  [ 5  6]]

 [[ 4  7]
  [ 9 10]
  [12 11]]]


In [155]:
# 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

import numpy as np

linearArray = np.linspace(0, 20, 6)
linearArray

array([ 0.,  4.,  8., 12., 16., 20.])

In [156]:
# 9. Make a Deep Copy of the above array

import copy

deepCopy = copy.deepcopy(linearArray)
deepCopy

array([ 0.,  4.,  8., 12., 16., 20.])

In [157]:
# 11. Concatenate these 3 arrays into a new array named 'newArray'...

import numpy as np

arrayB = np.array([[25, 16]])
arrayD = np.array([[11, 2], [13, 4]])
arrayE = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayB, arrayD, arrayE), axis=0)
print("Concatenated New Array\n", newArray)


Concatenated New Array
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [158]:
# 12. Sort 'newArray' in order into 'sortedArray'

import numpy as np

sortedArray = np.sort(newArray)
print("Sorted Array\n", sortedArray)

Sorted Array
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [159]:
# 13. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

import numpy as np

reshapedArray = sortedArray.reshape(2, 2, 3)
print("Reshaped Array\n", reshapedArray)

Reshaped Array
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]


In [160]:
# 14. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

import numpy as np

a, b = reshapedArray
#print("Reshaped Array", a, b)

c, d = a
print("\n", c)
print("\n", d)
e, f = b
print("\n", e)
print("\n", f)


 [16 25  2]

 [11  4 13]

 [ 7 81  5]

 [ 6 11 12]


In [161]:
# 15. Combine and sort the following arrays into one called 'comboArray' ...

import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

concArray= np.concatenate((one, two, three))
comboArray = np.sort(concArray)

print("Combo Array:\n", comboArray)



Combo Array:
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [162]:
# 16. Take 'comboArray' and perform the following slicing activities:

# print sec1 - the 2nd element
print("2nd element is", comboArray[1])

# print sec2 - all elements from the 3rd element to the last
print("All elements from 3rd to last", comboArray[2:])

# print sec3 - all elements from the 4th to the 14th elements
print("All elements from 4th to 14th", comboArray[3:14])

# print sec4 - the last 6 elements
print("Last 6 elements", comboArray[-6:])

# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print("All elements from 0 to 15 using negative number method", comboArray[-28:-10])

# print sec6 - from #20 every even element to the end
print("From #20", comboArray[16:27:2])

# print sec7 - from the last element moving forward, every 5th element.
print("From the last element moving forward, every 5th element", comboArray[::-5])


2nd element is 1
All elements from 3rd to last [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
All elements from 4th to 14th [ 3  4  5  6  7 10 11 12 13 14 15]
Last 6 elements [22 23 24 25 26 27]
All elements from 0 to 15 using negative number method [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
From #20 [20 22 24 26]
From the last element moving forward, every 5th element [27 22 15 10  3]


In [163]:
# 20. Using Series, create a DataFrame that looks like this:

import pandas as pd
import numpy as np

# courses = pd.Series(["Ingredients", "Quantity", "Unit"])
# fees = pd.Series([22000, 25000, 23000])
# discount = pd.Series([1000, 2300, 1000])
# # print(courses)
# # print(fees)
# # print(discount)

# # combining multiple series
# df = pd.concat([courses, fees, discount], axis=1)
# #print(df)

# add column names
ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name="Ingredients")
quantity = pd.Series([4, 1, 2, 1], name="Quantity")
unit = pd.Series(["cups", "cup", "large", "can"], name="Unit")
df = pd.concat([ingredients, quantity, unit], axis=1)
index_labels = ['', '', '', '']
ingredients.index = index_labels
quantity.index = index_labels
unit.index = index_labels
df = pd.concat([ingredients, quantity, unit], axis=1)
df

Ingredients  Quantity   Unit
       Flour         4   cups
        Milk         1    cup
        Eggs         2  large
        Spam         1    can

In [164]:
#21 Take this data and create a DataFrame named studentData

import pandas as pd

stdData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(stdData)
studentData


Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [165]:
# 22 Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData["Deserts"] = deserts
studentData


Name  Height Qualification  address  Age        Pets           sport   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts  \
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

In [166]:
# 23 Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by=["Name", "address"], inplace=True)
#studentData.sort_values(by=["address"], inplace=True)
studentData

Name  Height Qualification  address  Age        Pets           sport   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

In [167]:
# 24 Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv("cows_and_goats.csv")

In [168]:
# 25 (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

import pandas as pd

vegetables = pd.DataFrame([["Tomato", "Red"], ["Okra", "Green"]], columns=["Vegetables", "Color"])
vegetables.to_csv("vegetables.csv", index=False)
df = pd.read_csv("vegetables.csv")
#print(df)

df1 = df.replace(to_replace="Tomato", value="Pepper")
#print(df1)
df1.to_csv("Updated vegetables.csv", index=False)